config/routes.rb
Ebookdb::Application.routes.draw do
  devise_for :users
  resources :books

  root :to => 'ebook#index'
  get "ebook/index"
  post "lists/create"
  get "lists/index"
  resources :lists

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id             :integer          not null, primary key
#  title          :string(255)
#  author         :string(255)
#  genre          :string(255)
#  description    :text
#  related_series :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :author, :description, :genre, :related_series, :title
  has_many :lists, :dependent => :destroy
end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  book_id    :integer
#  title      :string(255)
#  chapter    :integer
#  page       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class List < ActiveRecord::Base
  attr_accessible :book_id, :chapter, :page, :title, :user_id
  belongs_to :user
  belongs_to :book

  after_initialize :init

  def init
  	self.page = 1
  	self.chapter = 1
  end

  def self.add_update_list(user_id, book_id, title)
  	user = User.find(user_id)
  	data_list = user.lists.where(:book_id => book_id).first

		if title.blank?
  		data_list.destroy
  	elsif data_list.present?
  		data_list.update_attributes(:title => title)
  	else
  		List.create(:user_id => user_id, :book_id => book_id, :title => title)
			# list.save

  	end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  username               :string(255)
#  location               :string(255)
#  gender                 :string(255)
#  birthday               :string(255)
#  is_admin               :boolean
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
  has_many :lists
  has_many :books, through: :lists

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @user = User.find(current_user.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    @books = Book.all
    @id = "row_#{params[:id]}"

    respond_to do |format|
      format.html { redirect_to books_url }
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/ebook_controller.rb
class EbookController < ApplicationController
  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
# binding.pry
    user = User.find(current_user.id)
    book = Book.find(params[:book_id])

    list = List.add_update_list(current_user.id, params[:book_id], params[:list_title])

    respond_to do |format|
      format.html { render :nothing => true }
      format.js
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

	def find_list_title(id)
		record = @user.lists.where(:book_id => id).first
		record.present? ? record.title : nil
	end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <div id="error_explanation">
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/ebook_helper.rb
module EbookHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :genre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :genre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :related_series, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :related_series, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn' %>
  </div>
<% end %>

app/views/books/_showbooks.html.erb
    <% @books.each do |book| %>
      <tr>
        <% if current_user.present? %>
        <td><%= if current_user.is_admin then check_box_tag("book[]", book.id) end %></td>
        <% end %>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.description %></td>
        <td><%= book.related_series %></td>
        <td>
          <% if current_user.present? %>
          <% if current_user.is_admin %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      remote: true,
                      :class => 'btn btn-mini btn-danger', id: "row_#{book.id}" %>
          <% else %>
            <%= select_tag "lists", options_for_select(["Reading", "Wish", "Complete", "Ignore"], find_list_title(book.id)), prompt: "Put this on list...", :onchange => "ajax_function(#{book.id});", :id => "list_#{book.id}" %>
          <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>

app/views/books/destroy.js.erb
var parent_tr = $("#<%=j @id %>").parent().parent();

parent_tr.fadeOut('slow', function(){ 
	
$('.index').html("<%=j render 'books/showbooks' %>");

});

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <% if current_user.present? %>
        <th><%= if current_user.is_admin then check_box_tag("select_all")end %></th>
      <% end %>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:related_series) %></th>
      <% if current_user.present? %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody class="index">
  <%= render 'books/showbooks' %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @book.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @book.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @book.genre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @book.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:related_series) %>:</strong></dt>
  <dd><%= @book.related_series %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/ebook/index.html.erb
<h1>Ebook#index</h1>
<p>Find me in app/views/ebook/index.html.erb</p>

app/views/layouts/_flash_message.html.erb
<p>
	<% flash.each do |name, msg| %>
	<div class="alert alert-block">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<div id="error_explanation">
			<%= content_tag :div, msg, :id => "flash_#{name}" %>

		</div>
	</div>

	<% end %>
<p>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to 'Home', root_path, class: "active" %></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
              <li><%= link_to 'Browse All', books_path%></li>
              <li class="dropdown">

              <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi <%= current_user.username %>!<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My List', lists_index_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
              <% else %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi guest, click me!<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Login', new_user_session_path %></li>
                <li><%= link_to 'Register', new_user_registration_path %></li>
              </ul>
              <% end %>

              </li>
              <li></li>

               <a class="btn menu-right" href="#"><i class="icon-align-justify"></i></a>
              	
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebookdb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  
  <div class="container">
  	<%= render 'layouts/flash_message' %>
  	
    <%= yield %>


  </div> <!-- /container -->


</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :book_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :book_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :chapter, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :chapter, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :page, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :page, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:book_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:chapter) %></th>
      <th><%= model_class.human_attribute_name(:page) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to list.id, list_path(list) %></td>
        <td><%= list.user_id %></td>
        <td><%= Book.find(list.book_id).title %></td>
        <td><%= list.title %></td>
        <td><%= list.chapter %></td>
        <td><%= list.page %></td>
        <td><%=l list.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @list.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:book_id) %>:</strong></dt>
  <dd><%= @list.book_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @list.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:chapter) %>:</strong></dt>
  <dd><%= @list.chapter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:page) %>:</strong></dt>
  <dd><%= @list.page %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lists_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_list_path(@list), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              list_path(@list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>